import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import StairsTransition from "@/components/StairsTransition";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <StairsTransition> */}
          {children}
          <elevenlabs-convai agent-id="agent_1001kbq27qjjeajtpb778dztghpw"></elevenlabs-convai>
          <script src="https://unpkg.com/@elevenlabs/convai-widget-embed" async type="text/javascript"></script>
          <script
			src="https://cdn.botpress.cloud/webchat/v3.2/inject.js"
			defer></script>
		<script
			src="https://files.bpcontent.cloud/2025/07/26/14/20250726145316-HL7LMT4C.js"
			defer></script>
        {/* </StairsTransition> */}
      </body>
    </html>
  );
}
